apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_PASSWORD: "django_password"
  POSTGRES_HOST: "db"
  ALLOWED_HOSTS: "*"