apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "secrets.POSTGRES_PASSWORD is required" .Values.secrets.POSTGRES_PASSWORD | quote }}
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY is required" .Values.secrets.DJANGO_SECRET_KEY | quote }}